<H2>Trading Software</H2>
<UL>
<LI><A HREF="https://themerkle.com/top-6-bitcoin-trading-bots/">
Top 6 Bitcoin Trading Bots</A></LI>
<LI><A HREF="https://www.cryptohopper.com/">
Cryptohopper</A></LI>
<LI><A HREF="https://cryptotrader.org/">
Cryptotrader Cloud-based Automated Trading Solution</A></LI>
<LI><A HREF="https://bitcointalk.org/index.php?topic=507103.0">
C.A.T. Cryptocurrency Automatic Trader 5.1</A> (Lots of useful Api Activation Instructions, scroll down a bit)</LI>
<LI><A HREF="https://www.sitepoint.com/build-cryptocurrency-auto-trader-bot-php/">
How to Build a Cryptocurrency Auto-Trader Bot with PHP</A></LI>
<LI>Arbitrage Strategies & Software
<UL>
    <LI><A HREF="https://github.com/butor/blackbird">
    Blackbird Bitcoin Arbitrage: a long/short market-neutral strategy</A></LI>
    <LI><A HREF="https://www.tokenspread.com/">
    Token Spread - Crypto spread monitoring and alerts</A></LI>
    <LI><A HREF="https://medium.com/spreadstreet/a-super-simple-cryptocurrency-arbitrage-spreadsheet-for-finding-mismatched-prices-a6e8b12dd8b0">
    A Super Simple Cryptocurrency Arbitrage Spreadsheet</A> (also <A HREF="https://www.quora.com/Is-Bitcoin-arbitrage-buy-them-on-one-exchange-at-a-certain-rate-and-sell-them-on-another-exchange-at-a-higher-rate-a-feasible-trading-strategy-If-not-why">here</A>)</LI>
    </UL></LI>
</UL>
<TABLE BORDER=6 CELLSPACING=3 CELLPADDING=3 WIDTH="100%" >
<TH WIDTH=100% COLSPAN=3><A HREF="https://a16z.com/2018/02/10/crypto-readings-resources/">Cryptocurrency Links &amp; Resources at Andreessen Horowitz</A><BR/>My Cryptocurrency Links &amp; Resources</TH>
<TR>
<TD ALIGN=LEFT VALIGN=TOP WIDTH=33% COLSPAN=1>
    <B>Articles &amp; Guides</B>
    <LI><A HREF="https://medium.com/@abody/blockchain-how-to-choose-the-right-tech-for-your-business-aa4597d7ee7c">Overview of types of blockchains, coins, tokens, validation, etc</A> (excellent start)</LI>
    <LI><B>Wikipedia articles</B>
        <UL>
            <LI><A HREF="https://en.wikipedia.org/wiki/Blockchain">
                 Blockchain</A></LI>
            <LI><A HREF="https://en.wikipedia.org/wiki/Cryptocurrency">
                 Cryptocurrency</A></LI>
            <LI><A HREF="https://en.wikipedia.org/wiki/Bitcoin">
                 Bitcoin</A></LI>
            <LI><A HREF="https://en.wikipedia.org/wiki/Ethereum">
                 Ethereum</A>
                 <UL>
                 <LI><A HREF="https://en.wikipedia.org/wiki/Smart_contract">
                     Smart Contract</A></LI>
                 </UL></LI>
            <LI><A HREF="https://en.wikipedia.org/wiki/Monero_(cryptocurrency)">
                 Monero cryptocurrency</A></LI>
            <LI><A HREF="https://en.wikipedia.org/wiki/Vertcoin">
                 Vertcoin cryptocurrency</A></LI>
            <LI><A HREF="https://en.wikipedia.org/wiki/Hyperledger">
                 Hyperledger</A></LI>
            <LI><A HREF="https://en.wikipedia.org/wiki/Cryptographic_nonce">
                 Cryptographic nonce</A></LI>
            <LI><A HREF="https://en.wikipedia.org/wiki/List_of_cryptocurrencies">
                 List of Cryptocurrencies</A></LI>
        </UL></LI>
        <LI><B>Guides</B>
        <UL>
            <LI><A HREF="https://decentralize.today/your-dapp-doesnt-need-a-token-1447375d9c67">Your DApp Doesn&apos;t Need a Token</A> A guide to preventing irresponsible token sales for DApps that don&apos;t need a token.</LI>
            <LI><A HREF="https://medium.com/@apompliano/the-official-guide-to-tokenized-securities-44e8342bb24f">Guide to Tokenized Securities</A></LI>
            <LI><A HREF="https://99bitcoins.com/guide-ethereum-mining-how-to-mine-ethereum/">Beginner's Guide to Ethereum Mining in 2017 - How to Mine Ethereum on Your PC?</A></LI>
            <LI><A HREF="http://ethdocs.org/en/latest/mining.html#mining">Ethereum Homestead Mining Guide</A></LI>
            <LI><A HREF="https://www.cryptocompare.com/mining/guides/how-to-use-ethos-to-manage-your-ether-mining/">Using ethOS for Ethereum Mining</A></LI>
            <LI><A HREF="http://forum.ethereum.org/discussion/8886/quick-start-guide-to-mine-ethereum#latest">Quick Start Guide to Mine Ethereum</A></LI>
            <LI><A HREF="https://eth.nanopool.org/help">Quick Start Guide to Mine Ethereum on Windows</A> (Nanopool)</LI>
            <LI><A HREF="https://blockgeeks.com/guides/what-is-ethereum/">Beginners Guide to Ethereum</A> by BlockGeeks</LI>
            <LI><A HREF="https://ethminingforbeginners.wordpress.com/">Ethereum Pool Mining Guide</A></LI>
            <LI><A HREF="http://www.cryptobadger.com/category/guides/">
                Guides at CryptoBadger</A></LI>
            <LI><A HREF="https://mtlynch.io/windows-sia-mining/">A Beginner's Guide to Mining Siacoin</A></LI>
            <LI><A HREF="https://www.reddit.com/r/decred/comments/6vljah/how_do_i_stake_decred_and_what_profits_can_you/">
                 How to Stake Decred (PoS)</A></LI>
            <LI><A HREF="https://www.nicehash.com/help/amd-mining">
                AMD Mining with NiceHash</A></LI>
            <LI><A HREF="https://www.nicehash.com/help/nvidia-mining">
                NVIDIA Mining with NiceHash</A></LI>
        </UL></LI>
</TD>
<TD ALIGN=LEFT VALIGN=TOP WIDTH=34% COLSPAN=1>
    <B>Exchanges/Analysis/Pools</B>
        <UL>
            <LI><A HREF="https://www.binance.com/">
                 Binance Cryptocurrency Exchange</A></LI>
            <LI><A HREF="https://bittrex.com/Market/Index?MarketName=BTC-ETH">
                 Bittrex Crypto Trading Platform &amp; Exchange</A></LI>
            <LI><A HREF="https://exchange.gemini.com/">
                 Gemini Cryptocurrency Exchange</A></LI>
            <LI><A HREF="https://poloniex.com/exchange">
                 Poloniex Digital Asset Exchange</A></LI>
            <LI><A HREF="https://www.worldcoinindex.com/">
                 Cryptocurrency Price Charts &amp; Stats</A></LI>
            <LI><A HREF="https://coincheckup.com/">
                 Cryptocoin Analysis &amp; Investment Stats</A></LI>
            <LI><A HREF="https://coinmarketcap.com/coins/">
                 Cryptocurrency Market Capitalizations</A></LI>
            <LI><A HREF="https://www.techpowerup.com/">
                 TechPowerUp Reviews, Forums, GPU Database</A></LI>
            <LI><B>Pools</B>
            <UL>
                <LI><A HREF="http://btcg.miningspeed.com/">
                    Bitcoin Gold Pool at Miningspeed</A></LI>
                <LI><A HREF="http://zpool.ca/">
                    ZPOOL Multi-Pool</A></LI>
                <LI><A HREF="https://miningpoolhub.com/">
                    Mining Pool Hub Multi-Pool</A></LI>
                <LI><B>NiceHash Pools</B>
                <UL>
                    <LI><A HREF="https://www.nicehash.com/pool-operators">
                        Information and guidelines for third-party pool operators and pool users</A> Example:
                        <A HREF="https://api.nicehash.com/api?method=buy.info">
                        https://api.nicehash.com/api?method=buy.info</A>
                        </LI>
                    <LI><A HREF="https://www.nicehash.com/compatible-pools">
                        NiceHash Compatible Pools</A></LI>
                </UL></LI>
                <LI><B>Peer-to-Peer Pools (p2pool)</B>
                <UL>
                    <LI><A HREF="http://p2pool.in/">
                        P2Pool Home</A></LI>
                    <LI><A HREF="http://p2pool.org/community/">
                        P2Pool Community &amp; Resources</A></LI>
                    <LI><A HREF="https://en.bitcoin.it/wiki/P2Pool">
                        Bitcoin P2Pool Wiki</A></LI>
                    <LI><A HREF="https://github.com/p2pool/p2pool">
                        Bitcoin P2Pool on GitHub</A></LI>
                    <LI><A HREF="https://github.com/robvanmieghem/siapool">
                        SIA P2Pool on GitHub</A></LI>
                    <LI><A HREF="https://github.com/vertcoin/p2pool-vtc">
                        Vertcoin (VTC) P2Pool on GitHub</A></LI>
                </UL></LI>
            </UL></LI>
        </UL></LI>
</TD>
<TD ALIGN=LEFT VALIGN=TOP WIDTH=33% COLSPAN=1>
    <B>Altcoins/Projects</B>
        <UL>
            <LI><A HREF="https://protocol.ai/">
                 <B>Protocol Labs</B></A> - IPFS, Filecoin, libp2p, IPLD, Multiformats</LI>
            <LI><A HREF="https://www.cardanohub.org/en/home/">
                 <B>Cardano</B> proof-of-stake blockchain</A> - smart contract platform with advanced features</LI>
            <LI><A HREF="https://ethereum.org/">
                 <B>Ethereum</B> Project</A>
            <UL>
            <LI><A HREF="https://github.com/ethereum/mist/releases">
                 Mist - the Ethereum Wallet</A> (releases)</LI>
            <LI><A HREF="https://auth0.com/blog/an-introduction-to-ethereum-and-smart-contracts/">
                 An Introduction to Ethereum and Smart Contracts</A> (part 1)</LI>
            <LI><A HREF="https://auth0.com/blog/an-introduction-to-ethereum-and-smart-contracts-part-2/">
                 An Introduction to Ethereum and Smart Contracts</A> (part 2)</LI>
            <LI><A HREF="https://auth0.com/blog/an-introduction-to-ethereum-and-smart-contracts-part-3/">
                 An Introduction to Ethereum and Smart Contracts</A> (part 3)</LI>
            <LI><A HREF="https://www.nytimes.com/2017/10/01/technology/what-is-ethereum.html">
                 Understanding Ethereum, Bitcoin’s Virtual Cousin</A> (NY Times)</LI>
                 </UL></LI>
            <LI><A HREF="https://litecoin.org/">
                 <B>Litecoin Project</B></A></LI>
            <LI><A HREF="https://github.com/litecoin-project/litecoin">
                 <B>Litecoin Github Repository</B></A></LI>
            <LI><A HREF="https://monacoin.org/">
                 <B>Monacoin Project</B></A> - the 1st Japanese Cryptocurrency</LI>
            <LI><A HREF="https://github.com/monacoinproject/monacoin">
                 <B>Monacoin Github Repository</B></A></LI>
            <LI><A HREF="https://vertcoin.org/">
                 <B>Vertcoin</B> Cryptocurrency</A></LI>
            <LI><A HREF="https://github.com/vertcoin/monocle">
                 <B>Monocle</B> Cryptocurrency</A> (Monocle is a <A HREF="https://en.wikipedia.org/wiki/Vertcoin#Merged_mining">merge mineable</A> N-factor Scrypt coin, released by the Vertcoin developers)</LI>
            <LI><A HREF="https://gist.github.com/veqtrus/e2b7c34d9c8b3ad285209ae1b13ca2b2">
                 Vertcoin <B>P2Pool</B> Setup Guide</A></LI>
            <LI><A HREF="https://www.hyperledger.org/">
                 <B>Hyperledger</B> Project</A></LI>
            <LI><B>Zcash</B> open source cryptocurrency with strong privacy protections</A></LI>
            <UL>
                <LI><A HREF="https://z.cash">
                    Zcash official site</A></LI>
                <LI><A HREF="https://z.cash/support/getting-started.html">
                    Zcash getting started</A></LI>
                <LI><A HREF="https://github.com/zcash/zcash/wiki/1.0-User-Guide">
                    The official Zcash 1.0 User Guide</A></LI>
                <LI><A HREF="https://z.cash/blog/anatomy-of-zcash.html">
                    Anatomy of a Zcash Transaction</A></LI>
                <LI><A HREF="https://www.zcashcommunity.com/">
                    Zcash Community site</A></LI>
                <LI><A HREF="https://z.cash/blog/zcash-private-transactions.html">
                    How Private Transactions Work</A> (shielded address transactions)</LI>
            </UL></LI>
            <LI>
             <A HREF="https://namecoin.org/">
             <B>Namecoin</B></A> (key/value pair registration and transfer system)</LI>
            <LI>
             <B>CryptoCards</B> - my 1st DApp, buy and sell baseball cards, an ERC721 smart contract for trading collectibles</LI>
        </UL></LI>
</TD>
</TR>
<TR>
<TD ALIGN=LEFT VALIGN=TOP WIDTH=67% COLSPAN=2>
<TABLE BORDER=3 CELLSPACING=1 CELLPADDING=1 WIDTH="100%" >
<TH WIDTH=100% COLSPAN=2>Mining Software</TH>
<TR>
<TD ALIGN=LEFT VALIGN=TOP WIDTH=50% COLSPAN=1>
    <UL>
    <LI><B>Windows only</B>
      <UL>
        <LI><A HREF="http://www.awesomeminer.com/">
             Awesome Miner</A></LI>
        <LI><A HREF="https://miner.nicehash.com/">
             NiceHash</A>
             <UL>
                 <LI><A HREF="https://github.com/NiceHash/NiceHashMinerLegacy/wiki/Getting-started"> NiceHash Getting Started</A> (Windows)</LI>
                 <LI><A HREF="https://www.nicehash.com/cpu-gpu-mining">
                     NiceHash Miner Download</A> (Equihash USA Stratum: stratum+tcp://equihash.usa.nicehash.com:3357)</LI>
                 <LI><A HREF=
                     "https://www.nicehash.com/profitability-calculator">
                     NiceHash Profitability Calculator</A></LI>
             </UL></LI>
        <LI><A HREF="http://www.multiminerapp.com/">
             MultiMiner</A> (Windows but runs under Mono as well)
             <UL>
             <LI><A HREF="https://github.com/nwoolls/MultiMiner">
                 MultiMiner's Github source repository</A></LI>
             </UL></LI>
        <LI><A HREF="https://easyminer.net/">
             EasyMiner</A></LI>
      </UL></LI>
    <LI><B>Multi-platform</B>
      <UL>
        <LI>
         <A HREF="https://github.com/poolgold/ClaymoreBTGMiner/releases">
             Claymore Bitcoin Gold Miner</A></LI>
         <A HREF="https://github.com/nanopool/Claymore-Dual-Miner/releases">
             Claymore Dual Miner</A></LI>
        <LI><A HREF="https://github.com/nicehash/sgminer">
             sgminer</A></LI>
        <LI><A HREF="https://minergate.com/altminers/ethminer">
             MinerGate Supported Miners</A></LI>
        <LI><A HREF="https://github.com/decred/gominer">
             gominer - Go based GPU miner for Decred</A>
             (Linux &amp; Windows)</LI>
        <LI><A HREF="https://zcashminers.org/submissions">
             Winners of Zcash Open Source Miner competition</A>
            <UL>
            <LI><A HREF="https://github.com/xenoncat/equihash-xenon">
                 Equihash-Xenon</A></LI>
            <LI><A HREF="https://github.com/mbevand/silentarmy">
                 SilentArmy</A></LI>
            <LI><A HREF="https://github.com/tromp/equihash">
                 Equihash-Tromp</A></LI>
            <LI><A HREF="https://github.com/nginnever/zogminer">
                 Zogminer</A></LI>
        </UL></LI>
        <LI><A HREF="https://www.reddit.com/r/vertcoin/comments/68pmmy/setup_guides/">
            Mining Vertcoin</A></LI>
        <LI><A HREF="https://www.techpowerup.com/vgabios/">
            Video BIOS Collection</A></LI>
      </UL></LI>
    </UL></LI>
</TD>
<TD ALIGN=LEFT VALIGN=TOP WIDTH=50% COLSPAN=1>
    <UL>
        <LI><B>Monero (XMR) Miners</B>
        <UL>
            <LI><A HREF="https://github.com/fireice-uk/xmr-stak-amd">
                XMR-Stak AMD GPU miner</A> (Linux/Windows)</LI>
            <LI><A HREF="https://github.com/fireice-uk/xmr-stak-nvidia">
                XMR-Stak NVIDIA GPU miner</A> (Linux/Windows)</LI>
            <LI><A HREF="https://github.com/fireice-uk/xmr-stak-cpu">
                XMR-Stak CPU miner</A> (Windows/Linux/BSD)</LI>
            <LI><A HREF="https://github.com/xmrig/xmrig-nvidia">
                XMRig GPU miner</A> (Windows + NVIDIA)</LI>
            <LI><A HREF="https://github.com/xmrig/xmrig">
                XMRig CPU miner</A> (Windows)</LI>
        </UL></LI>
        <LI><B>Open Source Miners used by EthOS</B>
        <UL>
            <LI><A HREF="https://github.com/Genoil/cpp-ethereum/">
            ethminer</A></LI>
            <LI><A HREF="https://github.com/genesismining/sgminer-gm/">
            sgminer-gm</A></LI>
            <LI><A HREF="https://github.com/tpruvot/ccminer/">
            ccminer</A></LI>
            <LI><A HREF="https://github.com/mbevand/silentarmy/">
            silentarmy</A></LI>
            <LI><A HREF="https://github.com/ystarnaud/amdmeminfo/">
            amdmeminfo</A></LI>
            <LI><A HREF="https://github.com/ohgodacompany/ohgodatool">
            ohgodatool</A></LI>
        </UL></LI>
        <LI><B>MultiPoolMiner</B> (works with MiningPoolHub, Zpool, &amp; Nicehash)
        <UL>
            <LI><A HREF="https://github.com/aaronsace/MultiPoolMiner">
            MultiPoolMiner Github Home</A></LI>
            <LI><A HREF="https://miningpoolhub.com/">
            MiningPoolHub Home</A></LI>
            <LI><A HREF="https://bitcointalk.org/index.php?topic=472510.0">
            MiningPoolHub on Bitcoin Talk Forum</A></LI>
            <LI><A HREF="https://sia.today/48/miningpoolhub-with-multipoolminer-multialgo-auto-exchange">
            Ultimate Guide for MiningPoolHub and MultiPoolMiner Multiple Algorithm Miner</A></LI>
            <LI><A HREF="https://youtu.be/7mayAT-7APM">
            MultiPoolMiner Setup Video</A> (10 minutes)</LI>
            <LI><A HREF="https://youtu.be/evbQi45k75g">
            MultiPoolMiner with MiningPoolHub Setup Video</A> (21 minutes)</LI>
        </UL></LI>
        <LI>
          <A HREF="https://whattomine.com/">
             <B>What To Mine</B></A> (calculator for coins relative to ETH)</LI>
    </UL></LI>
</TD></TR>
</TABLE>
</TD>
<TD ALIGN=LEFT VALIGN=TOP WIDTH=33% COLSPAN=1>
    <B>Decentralized Apps (DApps)</B>
        <UL>
            <LI><A HREF="https://singularitynet.io/">
                SingularityNET - Platform for Decentralized AI Economy</A></LI>
            <LI><A HREF="https://github.com/singnet/singnet">
                SingularityNET Github Repository</A></LI>
            <LI><A HREF="https://www.civic.com/">
                Civic - Secure Identity Platform via Blockchain</A></LI>
            <LI><A HREF="https://tokensale.civic.com/CivicTokenSaleWhitePaper.pdf">
                Civic white paper on Identity Verification and Identity Management via Blockchain</A></LI>
            <LI><A HREF="https://geth.ethereum.org/">
                GO Ethereum</A> (Official GO Implementation of the Ethereum Protocol)</LI>
            <LI><A HREF="https://github.com/ethereum/go-ethereum">
                Official GO Implementation of the Ethereum Protocol</A> (Github)</LI>
            <LI><A HREF="http://www.bspend.com/etherization">
                Etherization GUI</A>
                - Etherization is a Civilization like game based on Ethereum blockchain</LI>
            <LI><A HREF="https://blog.localethereum.com/how-our-escrow-smart-contract-works/">
                How the localethereum Escrow Smart Contract Works</A></LI>
            <LI><A HREF="https://www.stateofthedapps.com/">
                The DApps, large collection of decentralized apps</A></LI>
            <LI><A HREF="https://github.com/ConsenSys/smart-contract-best-practices/">
                Smart Contract Best Practices</A></LI>
            <LI><A HREF="https://github.com/gridplus">
                Grid+ Energy Blockchain Github Repositories</A></LI>
            <LI><A HREF="https://github.com/JoinColony/colonySale">
                GPL Smart Contract Code for Colony Token Crowdsale</A></LI>
            <LI><A HREF="https://wizard.oracles.org/">
                ICO Wizard</A></LI>
            <LI><A HREF="https://coincenter.org/entry/what-does-it-mean-to-issue-a-token-on-top-of-ethereum">
                What does it mean to issue a token &quot;on top of&quot; Ethereum?</A></LI>
        <LI><B>Blockchain</B>
        <UL>
            <LI><A HREF="https://www.multichain.com/">
                MultiChain private blockchain platform</A> - build and deploy blockchain applications
            <UL><LI><A HREF="https://www.multichain.com/download/MultiChain-White-Paper.pdf">
                MultiChain White Paper</A> (PDF)</LI>
            </UL></LI>
            <LI><A HREF="https://www.scytl.com/wp-content/uploads/2017/01/Distributed-Immutabilization-of-Secure-Logs_Scytl.pdf">
                Distributed immutabilization of secure logs</A> (PDF)</LI>
            <LI><A HREF="https://www.openchain.org/">
                Openchain</A> - open source distributed ledger technology (not really blockchain, more "transaction" chain)</LI>
            <LI><A HREF="https://medium.freecodecamp.org/from-what-is-blockchain-to-building-a-blockchain-within-an-hour-4e738efc819d">
                Building a blockchain in less than an hour</A> by freeCodeCamp</LI>
            <LI><A HREF="https://blockgeeks.com/guides/what-is-blockchain-technology/">
                What is Blockchain Technology</A> - step by step guide by Blockgeeks</LI>
            <LI><A HREF="https://www.ibm.com/blockchain/offerings.html">
                Blockchain solutions and services at IBM</A></LI>
            <LI><A HREF="https://developers.blockapps.net/">
                BlockApps Develpers Website</A></LI>
            <LI><A HREF="https://www.coindesk.com/">
                Digital Asset &amp; Blockchain Daily News</A></LI>
        </UL></LI>
        <LI><B>Blockstack</B> - an alternate DNS &amp; public-key infrastructure providing a network for DApps built on top of the Bitcoin blockchain
        <UL>
        <LI><A HREF="https://blockstack.org/">
               Blockstack Website</A></LI>
        <LI><A HREF="https://en.wikipedia.org/wiki/Blockstack">
               Blockstack Wikipedia Article</A></LI>
        <LI><A HREF="https://github.com/blockstack">
               Blockstack Github</A>
               <UL>
               <LI><A HREF="https://github.com/blockstack/blockstack">
               Blockstack Doc &amp; Protocols</A></LI>
               <LI><A HREF="https://github.com/blockstack/blockstack-core">
               Blockstack Reference Implementation</A></LI>
               <LI><A HREF="https://github.com/blockstack/blockstack-browser">
               Blockstack Browser</A></LI>
               <LI><A HREF="https://github.com/blockstack/blockstack.js">
               Blockstack Identity, Auth, and Storage Library</A></LI>
               <LI><A HREF="https://github.com/blockstack/blockstack-explorer">
               Blockstack Block Explorer</A></LI>
               <LI><A HREF="https://github.com/blockstack/gaia">
               Blockstack Decentralized High-Performance Storage (GAIA)</A></LI>
               </UL></LI>
        <LI><A HREF="https://blockstack.org/whitepaper.pdf">
                Blockstack Technical Whitepaper</A></LI>
        </UL></LI>
        </LI>
        </UL>
</TD>
</TR>
<TR>
<TD ALIGN=LEFT VALIGN=TOP WIDTH=34% COLSPAN=1>
    <B>Forums/Community Doc/Talk</B>
        <UL>
            <LI><A HREF="http://www.ethdocs.org/en/latest/index.html">
                Ethereum Homestead Documentation</A>
                - by Ethereum Community Volunteers</LI>
            <LI><A HREF="https://bitcointalk.org/index.php">
                Bitcoin Talk</A></LI>
            <LI><A HREF="https://bitcointalk.org/index.php?board=160.0">
                Mining Altcoins on Bitcoin Talk</A></LI>
            <LI><A HREF="https://bitcointalk.org/index.php?board=199.0">
                Altcoin Mining Pools on Bitcoin Talk</A></LI>
            <LI><A HREF="https://forum.ethereum.org/">
                Ethereum Community Forum</A>
            <UL>
                <LI><A HREF="https://forum.ethereum.org/categories/services-and-decentralized-applications">
                  Ethereum Community Smart Contracts &amp; DApps Forum</A></LI>
                <LI><A HREF="https://forum.ethereum.org/categories/solidity">
                  Ethereum Community Solidity Forum</A></LI>
                <LI><A HREF="http://forum.ethereum.org/categories/mining">
                  Ethereum Community Mining Forum</A></LI>
            </UL></LI>
            <LI><A HREF="https://www.reddit.com/r/EtherMining/">
                EtherMining (Reddit)</A></LI>
            <LI><A HREF="https://www.reddit.com/r/EtherMining/wiki/software/apps/ethos">
                How to begin mining on ethOS (Reddit)</A></LI>
            <LI><A HREF="https://stackexchange.com/sites">
                StackExchange Sites</A>
            <UL>
            <LI><A HREF="https://bitcoin.stackexchange.com/">
                Bitcoin StackExchange Site</A></LI>
            <LI><A HREF="https://ethereum.stackexchange.com/">
                Ethereum StackExchange Site</A></LI>
            <LI><A HREF="https://ethereum.stackexchange.com/questions/3475/how-to-query-local-ethereum-blockchain-for-a-specified-transaction">
                How to query local Ethereum blockchain for specified transaction</A></LI>
            </UL></LI>
            <LI><A HREF="https://www.cryptocoinsnews.com/bitcoin-transaction-really-works/">
                How a Bitcoin Transcaction Works</A></LI>
            <LI><A HREF="https://www.steem.center/index.php?title=Main_Page">
                Steem Center Wiki</A></LI>
            <LI><B>Publications/Newsletters/Feeds</B>
            <UL>
            <LI><A HREF="https://themerkle.com/">
                The Merkle</A></LI>
            <LI><A HREF="https://hackernoon.com/blockchain/home">
                Hackernoon Blockchain</A></LI>
            <LI>Medium Tags
            <UL>
                <LI><A HREF="https://medium.com/tag/blockchain">
                    Medium articles tagged Blockchain</A></LI>
                <LI><A HREF="https://medium.com/tag/token-sale">
                    Medium articles tagged Token Sale</A></LI>
                <LI><A HREF="https://medium.com/tag/bitcoin">
                    Medium articles tagged Bitcoin</A></LI>
                <LI><A HREF="https://medium.com/tag/cryptocurrency">
                    Medium articles tagged Cryptocurrency</A></LI>
                <LI><A HREF="https://medium.com/tag/ethereum">
                    Medium articles tagged Ethereum</A></LI>
            </UL></LI>
            <LI><A HREF="https://decentralize.today/">
                DecentralizeToday</A></LI>
            <LI><A HREF="https://coincentral.com/">
                Coincentral</A></LI>
            <LI><A HREF="https://cointelegraph.com/">
                Cointelegraph</A></LI>
            </UL></LI>
            <LI><B>DApp Development / Security</B>
            <UL>
            <LI>
          <A HREF="https://github.com/ethereum/go-ethereum/wiki/Contract-Tutorial">
                Contract Tutorial</A> - compiling &amp deploying &amp; registering a contract, sending &amp; registering coins, etc</LI>
            <LI><A HREF="https://blog.zeppelin.solutions/onward-with-ethereum-smart-contract-security-97a827e47702">
                Ethereum Smart Contract Security</A> (Zeppelin blog)</LI>
            </UL></LI>
        </UL></LI>
</TD>
<TD ALIGN=LEFT VALIGN=TOP WIDTH=33% COLSPAN=1>
    <B>Tools &amp; SDKs</B>
        <UL>
          <LI><B>Ethereum</B>
          <UL>
            <LI><A HREF="https://github.com/ethereum/wiki/wiki/JSON-RPC">
                    Standard DApp JSON RPC API</A></LI>
            <LI><A HREF=
                 "https://github.com/ethereum/go-ethereum/wiki/Management-APIs">
                    Geth Specific Management APIs</A></LI>
            <LI><B>Solidity</B>
            <UL>
              <LI><A HREF="https://github.com/ethereum/solidity">
                    Solidity Contract-Oriented Programming Language</A></LI>
              <LI><A HREF="http://solidity.readthedocs.io/en/latest/">
                    Solidity Documentation</A></LI>
              <LI><A HREF="https://remix.ethereum.org/#version=soljson-v0.4.18+commit.9cf6e910.js">
                    Example of web-based Solidity IDE</A></LI>
              <LI><A HREF="https://medium.com/covee-network/here-are-the-best-courses-and-resources-for-learning-solidity-ethereum-dapps-600e18287381">
                    Solidity Courses &amp; Resources</A></LI>
              <LI><A HREF="https://en.wikipedia.org/wiki/Solidity">
                    Solidity Wikipedia article</A></LI>
            </UL></LI>
            <LI><B>Ethereum Tutorials</B>
            <UL>
              <LI><A HREF="https://ethereum.org/token">
                    Create Your Own Crypto Currency with Ethereum</A></LI>
              <LI><A HREF="https://www.ethereum.org/crowdsale">
                    Crowdfunding with Ethereum</A></LI>
              <LI><A HREF="https://www.ethereum.org/dao">
                    Create a Decentralized Autonomous Organization (DAO)</A></LI>
              <LI><A HREF="https://medium.com/@mvmurthy/full-stack-hello-world-voting-ethereum-dapp-tutorial-part-1-40d2d0d807c2">
                Hello World Voting Ethereum Dapp Tutorial</A></LI>
            </UL></LI>
            <LI><A HREF="https://medium.com/@andrenit/buildind-an-ethereum-playground-with-docker-part-1-introduction-80be173aaa7a">
                Building an Ethereum Playground with Docker</A></LI>
            <LI><A HREF="http://blog.jaumesola.com/setting-up-an-ethereum-node-on-the-rinkeby-testnet">
                Setting up an Ethereum node on the Rinkeby testnet</A></LI>
            <LI><A HREF="https://gist.github.com/cryptogoth/10a98e8078cfd69f7ca892ddbdcf26bc">
                How to get on Rinkeby Testnet in less than 10 minutes</A></LI>
          </UL></LI>
          <LI><B>EthOS</B>
          <UL>
            <LI><A HREF="https://www.reddit.com/r/Signatum/comments/6rs0u6/how_to_compile_and_mod_gpu_sgminer_on_ethos/">
                How to Compile and Mod GPU sgminer on EthOS</A></LI>
          </UL></LI>
          <LI><B>AMD</B>
          <UL>
            <LI><A HREF="http://developer.amd.com/tools-and-sdks/opencl-zone/">
                AMD OpenCL Zone</A></LI>
            <LI><A HREF=
                "https://github.com/GPUOpen-LibrariesAndSDKs/OCL-SDK/releases">
                AMD OpenCL SDK</A></LI>
            <LI><A HREF="https://ethereum.stackexchange.com/questions/1993/what-actually-is-a-dag">
                What is the DAG (Directed Acyclic Graph)</A>
                and why is it a problem for AMD GPUs</LI>
          </UL></LI>
          <LI><B>NVidia</B>
          <UL>
            <LI><A HREF="https://developer.nvidia.com/cuda-toolkit">
                NVIDIA CUDA Toolkit</A></LI>
            <LI><A HREF="http://docs.nvidia.com/cuda/">
                NVIDIA CUDA Toolkit Documentation</A></LI>
            <LI><A HREF="http://www.overclockersclub.com/guides/nvidia_gtx_1080ti_oc_guide/">
                GTX 1080 Ti Overclocking Guide</A></LI>
          </UL></LI>
          <LI><B>IPFS - InterPlanetary File System</B>
          <UL>
            <LI><A HREF="https://en.wikipedia.org/wiki/InterPlanetary_File_System">
                Wikipedia IPFS article</A></LI>
            <LI><A HREF="https://ipfs.io/docs/getting-started/">
                IPFS Getting Started</A></LI>
            <LI><A HREF="https://youtu.be/YIc6MNfv5iQ">
                How Merkle Trees Enable the Decentralized Web</A> (YouTube)</LI>
            <LI><A HREF="https://media.consensys.net/interplanetary-linked-computing-separating-merkle-computing-from-blockchain-computational-courts-1ade201ecf8a">
                Interplanetary Linked Computing: Separating Merkle Computing from Blockchain Computational Courts</A></LI>
            <LI><A HREF="https://github.com/dexioio/DiamondRegistry">
                DiamondRegistry example DApp with IPFS asset store</A></LI>
          </UL></LI>
          <LI><B>Off-Chain Resources &amp; Blockchain Oracles</B>
          <UL>
            <LI><A HREF="https://en.wikipedia.org/wiki/Smart_contract#The_Oracle_Problem">
                The Oracle Problem &amp; Types of Oracle</A> (Wikipedia)</LI>
            <LI><A HREF="https://medium.com/@YondonFu/off-chain-computation-solutions-for-ethereum-developers-507b23355b17">
                Off-Chain Computation Solutions for Ethereum Developers</A></LI>
            <LI><A HREF="https://coincentral.com/what-is-chainlink-a-beginners-guide-to-decentralized-oracles/">
                What is ChainLink? A Beginner's Guide to Decentralized Oracles</A></LI>
            <LI><A HREF="https://www.smartcontract.com/link">
                LINK Network Decentralized Oracle Network</A></LI>
            <LI><A HREF="https://cointelegraph.com/explained/blockchain-oracles-explained">
                Blockchain Oracles, Explained</A></LI>
          </UL></LI>
        </UL></LI>
</TD>
<TD ALIGN=LEFT VALIGN=TOP WIDTH=33% COLSPAN=1>
    <B>ERC721</B>
    <UL>
        <LI><B>ERC721 Standard Proposal</B></LI>
        <UL>
            <LI><A HREF="https://github.com/ethereum/EIPs/issues/721">ERC: Non-fungible Token Standard · Issue #721 · ethereum/EIPs</A></LI>
            <LI><A HREF="https://github.com/ethereum/EIPs/pull/841">EIP-721 Deed Standard by fulldecent · Pull Request #841 · ethereum/EIPs</A></LI>
        </UL>
      <LI><B>Sample ERC721 Dapps</B>
        <UL>
        <LI><A HREF="https://github.com/dexioio/DiamondRegistry">dexioio/DiamondRegistry: An example implementation of Dexio&#39;s diamond registry which uses ERC721 assets to control write permissions to an IPFS document store.</A></LI>
        <LI><A HREF="https://github.com/sunsingerus/eth-erc721-token">sunsingerus/eth-erc721-token</A></LI>
        <LI><B>CryptoKitties</B></LI>
        <UL>
            <LI><A HREF="https://www.cryptokitties.co/technical-details">CryptoKitties | Collect and breed digital cats!</A></LI>
            <LI><A HREF="https://github.com/axiomzen/cryptokitties-bounty/blob/master/CryptoKitty%20Basics.md">cryptokitties-bounty/CryptoKitty Basics.md at master · axiomzen/cryptokitties-bounty</A></LI>
            <LI><A HREF="https://github.com/m0t0k1ch1/ERC721-token-sample">m0t0k1ch1/ERC721-token-sample: a sample implementation of ERC721 (CryptoKitties ver.)</A></LI>
        </UL></LI>
        </UL>
        <LI><B>Trading Cards</B>
        <UL>
            <LI><A HREF="https://github.com/paulvidal/CryptoMons">paulvidal/CryptoMons: The trading plateform to exchange pokemon cards between players using ethereum</A></LI>
        </UL></LI>
        <LI><B>Development Tools &amp; Doc</B>
        <UL>
        <LI><A HREF="http://truffleframework.com/docs/">Documentation | Truffle Suite</A></LI>
        <LI><A HREF="http://truffleframework.com/docs/ganache/using">Working with Ganache | Truffle Suite</A></LI>
        <LI><A HREF="https://solidity.readthedocs.io/en/develop/">Solidity — Solidity 0.4.21 documentation</A></LI>
        <LI><A HREF="http://truffleframework.com/boxes/">Truffle Boxes | Truffle Suite</A></LI>
        <LI><A HREF="https://www.investopedia.com/terms/f/fungibility.asp">Fungibility</A></LI>
        <LI><A HREF="http://truffleframework.com/tutorials/pet-shop">Ethereum Pet Shop -- Your First Dapp | Truffle Suite</A></LI>
        <LI><A HREF="https://medium.com/blockchannel/the-anatomy-of-erc721-2576e40bfc5b">The Anatomy of ERC721 – BlockChannel – Medium</A></LI>
        <LI><A HREF="https://medium.com/loom-network/how-to-code-your-own-cryptokitties-style-game-on-ethereum-7c8ac86a4eb3">How to Code Your Own CryptoKitties-Style Game on Ethereum</A></LI>
        <LI><A HREF="http://truffleframework.com/tutorials/ethereum-overview">Ethereum Overview | Truffle Suite</A></LI>
        <LI><A HREF="https://github.com/fulldecent/EIPs/blob/patch-2/EIPS/eip-721.md">EIPs/eip-721.md at patch-2 · fulldecent/EIPs</A></LI>
        <LI><A HREF="http://truffleframework.com/tutorials/">Tutorials | Truffle Suite</A></LI>
        <LI><A HREF="https://medium.com/@bleev.in.tech/how-to-deploy-a-smart-contract-to-ethereum-testnet-e34fa5b10dd6">How to deploy a smart contract on ethereum testnet?</A></LI>
        <LI><A HREF="http://truffleframework.com/tutorials/robust-smart-contracts-with-openzeppelin">Robust Smart Contracts with OpenZeppelin | Truffle Suite</A></LI>
        <LI><A HREF="http://truffleframework.com/boxes/pet-shop">pet-shop Box | Truffle Suite</A></LI>
        <LI><A HREF="http://www.techtonet.com/how-to-install-and-execute-truffle-on-an-ubuntu-16-04/">How to install and execute Truffle on an Ubuntu 16.04 | Techtonet</A></LI>
        <LI><A HREF="https://www.ethpm.com/registry">Ethereum Package Registry</A></LI>
    </UL></LI>
</TD>
</TR>
</TABLE>
