<TABLE WIDTH=100% BORDER=6 CELLPADDING=3 CELLSPACING=3>
<TR>
<TD COLSPAN=3>
<TABLE WIDTH=100% BORDER=6 CELLPADDING=3 CELLSPACING=3><TR>
<TH WIDTH=50%><A HREF=dates.html>Upcoming Gigs</A></TH>
<TH WIDTH=50%><A HREF=halloween.html>Halloween Gig</A></TH>
</TR><TR>
<TH WIDTH=50%><A HREF=/b_tow/last.html>Last gig</A> was
<A HREF=/b_tow/next.html>Friday, September 15th</A> at 
<A HREF=/b_tow/next.html>Callahan's</A></TH>
<TH WIDTH=50%><A HREF=/b_tow/next.html>Next gig</A> is 
<A HREF=/b_tow/next.html>Wednesday, October 25th</A> at
<A HREF=/b_tow/next.html>The Catalyst</A>.
</TH>
</TR></TABLE></TD></TR>
<TR><TD COLSPAN=3>
<TABLE WIDTH=100% BORDER=6 CELLPADDING=3 CELLSPACING=3><TR>
<TD WIDTH=50% ALIGN=CENTER><A HREF=http://members.cruzio.com/~lovejoy/>
Paradise Recording Studio</TD>
<TD WIDTH=50% ALIGN=CENTER><A HREF=http://www.google.com/search?q=Burlacticus>
Search Google for Burlacticus</TD></TR>
</TD></TR></TABLE></TD></TR>
<TR>
<TD ALIGN=CENTER COLSPAN=3>
<B><I>Mad Funk Beats and Off-the-Wall Lyrics</I></B></TD></TR>
<TR>
<TH COLSPAN=3><A HREF=http://www.burlacticusundertow.com/>
Visit the Brand Spanking New Official Undertow Website!</A></TH></TR>
<TR>
<TH COLSPAN=3>Flyers</TH></TR>
<TR>
<TD COLSPAN=3 ALIGN=CENTER>
<A HREF=/btow/next.html>Friday, September 15th at Callahan's with Fuse</A>
</TD></TR>
<TR>
<TD ALIGN=CENTER>
<A HREF=/btow/spring2000.html>Spring 2000</A></TD>
<TD ALIGN=CENTER>
<A HREF=cat1.html>Catalyst (1/2000)</A></TD>
<TD ALIGN=CENTER>
<A HREF=/btow/summer2000.html>Summer 2000</A></TD>
</TR>
<TR>
<TD ALIGN=CENTER>
<A HREF=/btow/flyers/flyer_inv.JPG>Skinny's (6/11)</A></TD>
<TD ALIGN=CENTER>
<A HREF=/btow/flyers/burningman_front.JPG>Burning Man</A></TD>
<TD ALIGN=CENTER>
<A HREF=/btow/flyers/Cocodrie.JPG>Cocodrie Lounge</A></TD>
</TR>
</TABLE>
