<TABLE BORDER=6 CELLSPACING=3 CELLPADDING=3 WIDTH="100%" >
<TR>
<TD ALIGN=CENTER COLSPAN=6><A HREF="seti/index.html">
Search for Extra-Terrestrial Intelligence at SCO</A></TD></TR>
<TR>
<TD ALIGN=CENTER WIDTH="17%"><A HREF="animation.html">Anim</A></TD>
<TD ALIGN=CENTER WIDTH="17%"><A HREF="anthro.html">Anthro/Geo</A></TD>
<TD ALIGN=CENTER WIDTH="16%"><A HREF="exhibits.html">Art</A></TD>
<TD ALIGN=CENTER WIDTH="16%"><A HREF="astro.html">Astro</A></TD>
<TD ALIGN=CENTER WIDTH="17%"><A HREF="audio.html">Audio</A></TD>
<TD ALIGN=CENTER WIDTH="17%"><A HREF="browsers.html#CGI">CGI</A>
</TD>
</TR>
<TR>
<TD ALIGN=CENTER WIDTH="17%"><A HREF="entertain.html">Fun</A></TD>
<TD ALIGN=CENTER WIDTH="17%"><A HREF="graphics.html">Graphics</A></TD>
<TD ALIGN=CENTER WIDTH="16%"><A HREF="java.html">Java</A></TD>
<TD ALIGN=CENTER WIDTH="16%"><A HREF="stuff.html">Stuff</A></TD>
<TD ALIGN=CENTER WIDTH="17%"><A HREF="links.html">Links</A></TD>
<TD ALIGN=CENTER WIDTH="17%"><A HREF="lit.html">Lit</A></TD>
</TR>
<TR>
<TD ALIGN=CENTER WIDTH="17%"><A HREF="math.html">Math</A></TD>
<TD ALIGN=CENTER WIDTH="17%"><A HREF="misc.html">Misc</A></TD>
<TD ALIGN=CENTER WIDTH="16%"><A HREF="windows.html">Microsoft</A></TD>
<TD ALIGN=CENTER WIDTH="16%"><A HREF="music.html">Music</A></TD>
<TD ALIGN=CENTER WIDTH="17%"><A HREF="news.html">News</A></TD>
<TD ALIGN=CENTER WIDTH="17%"><A HREF="browsers.html#Perl">Perl</A>
</TD>
</TR>
<TR>
<TD ALIGN=CENTER WIDTH="17%"><A HREF="Poems/">Poetry</A></TD>
<TD ALIGN=CENTER WIDTH="17%"><A HREF="politics.html">Politics</A></TD>
<TD ALIGN=CENTER WIDTH="16%"><A HREF="http://www.cruzio.com/~hiram">Hiram</A>
</TD>
<TD ALIGN=CENTER WIDTH="16%"><A HREF="Quotes/quotes.html">Quotes</A></TD>
<TD ALIGN=CENTER WIDTH="17%"><A HREF="search.html">Search</A></TD>
<TD ALIGN=CENTER WIDTH="16%"><A HREF="sports.html">Sports</A></TD>
</TR>
<TR>
<TD ALIGN=CENTER WIDTH="16%"><A HREF="stock.html">Stock</A></TD>
<TD ALIGN=CENTER WIDTH="17%"><A HREF="video.html">Video</A></TD>
<TD ALIGN=CENTER WIDTH="17%"><A HREF="browsers.html#Misc">Web Misc</A>
</TD>
<TD ALIGN=CENTER WIDTH="17%"><A HREF="browsers.html#HTML">WebAuth</A>
</TD>
<TD ALIGN=CENTER WIDTH="17%"><A HREF="browsers.html">WWW</A></TD>
<TD ALIGN=CENTER WIDTH="17%"><A HREF="comment-form.html">Comments</A></TD>
</TR>
<TR>
<TD ALIGN=CENTER COLSPAN=2><A HREF="/b_tow/">
<B>Burlacticus Undertow</B></A></TD>
<TD ALIGN=CENTER COLSPAN=2><A HREF="/today.html">
On Today's Date In History</A></TD>
<TD ALIGN=CENTER COLSPAN=2><A HREF="/paulthorn/">
<B>Paul Thorn</B></A></TD>
</TR>
<TR><TD ALIGN=CENTER COLSPAN=6>
<!--#include file="sites.html" -->
</TD></TR>
</TABLE>
<P>
<!-- TABLE BORDER=5>
<TR><TD ALIGN=CENTER>
<FORM METHOD=GET ACTION=/cgi-bin/webglimpse/cruzio/vr/www.ronrecord.com/pub_html>
Search the full archive of Ronald Joe Record's Personal Pages
</TD></TR>

<TR><TD>
String to search for: <INPUT NAME=query size=30>
<INPUT TYPE=submit VALUE=Submit>
</FORM>
</TD></TR>
</TABLE -->
<P>
