<TABLE WIDTH=100% BORDER=6 CELLPADDING=3 CELLSPACING=3>
<TR>
<TD COLSPAN=3>
<TABLE WIDTH=100% BORDER=6 CELLPADDING=3 CELLSPACING=3><TR>
<TH WIDTH=100%><A HREF=dates.html>Tour Dates</A></TH>
</TR>
</TABLE></TD></TR>
<TR><TD COLSPAN=3>
<TABLE WIDTH=100% BORDER=6 CELLPADDING=3 CELLSPACING=3><TR>
<TD WIDTH=50% ALIGN=CENTER><A HREF=http://members.cruzio.com/~lovejoy/>
Paradise Recording Studio</TD>
<TD WIDTH=50% ALIGN=CENTER><A HREF=http://www.google.com/search?q=Burlacticus>
Search Google for Burlacticus</TD></TR>
</TD></TR></TABLE></TD></TR>
<TR>
<TD ALIGN=CENTER COLSPAN=3>
<B><I>Mad Funk Beats and Off-the-Wall Lyrics</I></B></TD></TR>
<TR>
<TH COLSPAN=3><A HREF=http://www.burlacticusundertow.com/>
Visit the Brand Spanking New Official Undertow Website!</A></TH></TR>
<TR>
<TH COLSPAN=3>Flyers</TH></TR>
<TR>
<TD ALIGN=CENTER>
<A HREF=/b_tow/next.html>Callahan's with Fuse</A>
</TD>
<TD ALIGN=CENTER>
<A HREF=/b_tow/aptosclub.html>Aptos Club</A>
</TD>
<TD ALIGN=CENTER>
<A HREF=/b_tow/cabletv.html>SC Comm. Cable TV</A>
</TD>
</TR>
<TR>
<TD ALIGN=CENTER>
<A HREF=/b_tow/spring2000.html>Spring 2000</A></TD>
<TD ALIGN=CENTER>
<A HREF=cat1.html>Catalyst (1/2000)</A></TD>
<TD ALIGN=CENTER>
<A HREF=/b_tow/summer2000.html>Summer 2000</A></TD>
</TR>
<TR>
<TD ALIGN=CENTER>
<A HREF=/b_tow/flyers/flyer_inv.JPG>Skinny's (6/11)</A></TD>
<TD ALIGN=CENTER>
<A HREF=/b_tow/flyers/burningman_front.JPG>Burning Man</A></TD>
<TD ALIGN=CENTER>
<A HREF=/b_tow/flyers/Cocodrie.JPG>Cocodrie Lounge</A></TD>
</TR>
</TABLE>
